### ISSUE TITLE
AutoHiC seems to be making changes, but results look same. 

### ISSUE THREAD

**Issue by kiratalreja3** [Jwindler/AutoHiC#10]
Hi, I have tested AutoHiC at least 5 times in the "onehic.py" mode, and every single time it seems to be making adjustments (As indicated by the infer_results folder) - but as soon as I use 3d-dna post review script to generate .hic map on the adjusted assembly, it looks exactly the same as what was supplied to AutoHiC. Am I missing something?

Before AutoHiC :
<img width="828" alt="Screenshot 2023-10-05 at 10 18 25 am" src="https://github.com/Jwindler/AutoHiC/assets/100812164/3e3420c1-8ffb-4c23-b3ca-5d30812a15d0">

After AutoHiC:
<img width="815" alt="Screenshot 2023-10-06 at 10 19 47 am" src="https://github.com/Jwindler/AutoHiC/assets/100812164/708fc766-332c-4ecf-8b19-2d7fa0fb147a">

`{"Raw error number": {"translocation": 3, "inversion": 0, "debris": 573}, "Score filtered error number": {"translocation": 3, "inversion": 0, "debris": 561}, "Length filtered error number": {"translocation": 1, "inversion": 0, "debris": 559}, "Length removed error number": {"translocation": 2, "inversion": 0, "debris": 2}, "Overlap filtered error number": {"debris": 365, "translocation": 1}, "Chromosome real length filtered error number": {"translocation": {"normal": 0, "abnormal": 1}, "inversion": {"normal": 0, "abnormal": 0}, "debris": {"normal": 45, "abnormal": 320}}}`

This is the error summary. 

Can you please help me out here?

Thanks

**Comment by kiratalreja3** [comment]
[autohic.e97171355.txt](https://github.com/Jwindler/AutoHiC/files/12825552/autohic.e97171355.txt)
Here is the log, and the .assembly files before and after

Before:
[base.ctg_info.assembly.txt](https://github.com/Jwindler/AutoHiC/files/12825554/base.ctg_info.assembly.txt)

After:
[adjusted.assembly.txt](https://github.com/Jwindler/AutoHiC/files/12825555/adjusted.assembly.txt)

**Comment by Jwindler** [comment]
These are normal operating conditions. There are many debris errors in the genome. These errors are small and usually require many iterations to remove. My suggestion is to stop running `onehic` once the translocation and inversion errors have been removed from the genome.
