### ISSUE TITLE
Onehic.py: list index out of range

### ISSUE THREAD

**Issue by mushroomOK** [Jwindler/AutoHiC#12]
Hi, when I used "onehic.py", I got the error "IndexError: list index out of range". I am unsure what the "list index" refers to. 
genome size: 3.3 Gb, hic size: 4.7 Gb. 

"slurm-3620847.log" provides more details. 
[slurm-3620847.log](https://github.com/Jwindler/AutoHiC/files/13246072/slurm-3620847.log)

**Comment by Jwindler** [comment]
Can you also send me the running command? It is best if you share the hic and assembly files with me and I can help you solve the problem locally. @mushroomOK

**Comment by Jwindler** [comment]
From the preliminary judgment of the log, it seems that you used the `genome.fasta` file as the input of `assembly`

**Comment by mushroomOK** [comment]
Thank you for your prompt response! After further investigation, I have confirmed that I used "genome.fasta" as the input for the "-asy" parameter, which was the root cause of the problem.
