### ISSUE TITLE
Hello author, I have configured the environment and files. Started running, but kept reporting the following error

### ISSUE THREAD

**Issue by Biomedical-CYZ** [Jwindler/AutoHiC#13]
[2023-11-14  16:54:06] autohic.py -> whole line:33 [INFO] : AutoHiC start running ...

[2023-11-14  16:54:06] autohic.py -> whole line:35 [INFO] : Get configuration items

[2023-11-14  16:54:06] autohic.py -> whole line:54 [INFO] : Check if the GPU is available
[2023-11-14  16:54:06] autohic.py -> whole line:60 [INFO] : GPU is available, AutoHiC will run on GPU

[2023-11-14  16:54:06] autohic.py -> whole line:69 [INFO] : Fastq file number is correct.

[2023-11-14  16:54:06] autohic.py -> whole line:86 [INFO] : Check genome length whether > 80 base
[2023-11-14  16:54:06] autohic.py -> whole line:102 [INFO] : Genome len < 80 base

[2023-11-14  16:54:06] autohic.py -> whole line:105 [INFO] : Stage 1: Run Juicer and  3d-dna
[2023-11-14  17:04:33] autohic.py -> whole line:109 [INFO] : Run Juicer and  3d-dna finished

[2023-11-14  17:04:33] autohic.py -> whole line:112 [INFO] : Stage 2: Select the min error number of  hic file

[2023-11-14  17:04:33] autohic.py -> whole line:127 [INFO] : Check the 0 file
[2023-11-14  17:04:33] mul_gen_png.py -> mul_process line:49 [INFO] : Multiple Process Initiating ...

[2023-11-14  17:04:33] hic_adv_model.py -> __init__ line:30 [INFO] : Base Model Initiating

[2023-11-14  17:04:33] hic_adv_model.py -> __init__ line:40 [INFO] : Create genome folder: /home/cyz/soft/AutoHiC/result/AutoHiC-test/autohic_results/0/png

File /home/cyz/soft/AutoHiC/result/AutoHiC-test/hic_results/3d-dna/ll.0.hic cannot be opened for reading

**Comment by Jwindler** [comment]
From your log, we can see that your environment is configured correctly and is running in GPU mode. It is recommended that you check the logs in the log folder of the reuslt directory to see if there is a problem. Thank you.

**Comment by Biomedical-CYZ** [comment]
Thank you for your answer
Juicer. TXT: / home/cyz/soft/AutoHiC/SRC/common/run. Sh: 47: / home/cyz/soft/ubuntu/AutoHiC/juicer/scripts/juicer. Sh: Not a directory

3 d - DNA. TXT: / home/cyz/soft/AutoHiC/SRC/common/run. Sh: 58: / home/cyz/soft/ubuntu/run/AutoHiC / 3 d - DNA - asm - pipeline. Sh: Insufficient authority
I use the juicer folder you provided, and now I have opened all the permissions of the folder, I wonder whether it is the problem of Juicer. sh?

**Comment by Biomedical-CYZ** [comment]
I think my juicer path setting is wrong, but you juicer provided 7 folders, which should I choose?

**Comment by Jwindler** [comment]
/ home/cyz/soft/ubuntu/AutoHiC/juicer @Biomedical-CYZ

**Comment by Biomedical-CYZ** [comment]
If I set JUICER_DIR = / home/cyz/soft/ubuntu/AutoHiC/juicer, complains/home/cyz/soft/AutoHiC/SRC/common/run. Sh: 47: /home/cyz/soft/ubuntu/AutoHiC/juicer/scripts/juicer.sh:  It is not a directory. The juicer folder you provided does not have Juicer.sh in the next directory, while the other folders in the next layer have Juicer.sh in the next layer

# Paths and system Settings
JOB_NAME=AutoHiC-test
AutoHiC_DIR=/home/cyz/soft/AutoHiC
RESULT_DIR=/home/cyzsoft/AutoHiC/result
N_CPU=40

# Data options
SPECIES_NAME=LL
REFERENCE_GENOME=/home/cyz/soft/ubuntu/AutoHiC/references/ll.fa

# Juicer options
JUICER_DIR=/home/cyz/soft/ubuntu/AutoHiC/juicer
FASTQ_DIR=/home/cyz/soft/ubuntu/AutoHiC/rawdata
ENZYME=DpnII


# 3D-DNA options
TD_DNA_DIR=/home/cyz/soft/ubuntu/AutoHiC/3d-dna
NUMBER_OF_EDIT_ROUNDS=2

# AutoHiC options
ERROR_PRETRAINED_MODEL=/home/cyz/soft/ubuntu/AutoHiC/error_model.pth
CHR_PRETRAINED_MODEL=/home/cyz/soft/ubuntu/AutoHiC/chr_model.pth

TRANSLOCATION_ADJUST=True
INVERSION_ADJUST=True
DEBRIS_ADJUST=True

ERROR_MIN_LEN=15000
ERROR_MAX_LEN=20000000
ERROR_FILTER_SCORE=0.9
ERROR_FILTER_IOU_SCORE=0.8


/AWS - scripts for running pipeline and postprocessing on AWS

/UGER - scripts for running pipeline and postprocessing on UGER (Univa)

/SLURM - scripts for running pipeline and postprocessing on SLURM

/LSF - scripts for running pipeline and postprocessing on LSF **BETA**

/CPU - scripts for running pipeline and postprocessing on a single CPU **BETA**   

I think I should set JUICER_DIR = / home/cyz/soft/ubuntu/AutoHiC/juicer/AWS？

**Comment by Jwindler** [comment]
no

**Comment by Biomedical-CYZ** [comment]
When set to/home/cyz you said/soft/ubuntu/AutoHiC/juicer, an error File /home/cyz/soft/AutoHiC/result/AutoHiC-test/hic_results/3d-dna/ll.0.hic cannot be opened for reading   juicer.txt an error /home/cyz/soft/AutoHiC/src/common/run.sh: 行 47: /home/cyz/soft/ubuntu/AutoHiC/juicer/scripts/juicer.sh: 不是目录

**Comment by Jwindler** [comment]
JUICER_DIR is the folder where the juicer software is located.

**Comment by Jwindler** [comment]
Maybe you need to add permissions to juicer.sh

**Comment by Biomedical-CYZ** [comment]
I'm very sorry, I amend the JUICER_DIR to software installation position, still an error/home/cyz/soft/AutoHiC/SRC/common/run. Sh: 47: / home/cyz/miniconda3 / envs/autohicpy39 / bin/juicer/scripts/juicer. Sh: not a directory

**Comment by Jwindler** [comment]
Can you send all your log files to me for review? This includes files in the `logs` folder and you [cfg-autohic.txt](https://github.com/Jwindler/AutoHiC/blob/main/cfg-autohic.txt)

**Comment by Biomedical-CYZ** [comment]
非常感谢您的帮助，我的微信是17396225596，qq是1206414925
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/14/2023 19:38 |
| To | Jwindler/AutoHiC ***@***.***> |
| Cc | Biomedical-CYZ ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [Jwindler/AutoHiC] Hello author, I have configured the environment and files. Started running, but kept reporting the following error (Issue #13) |

Maybe you need to add permissions to juicer.sh
