### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by lstxmu** [Jwindler/AutoHiC#14]
HI, 
[log.txt](https://github.com/Jwindler/AutoHiC/files/13712058/log.txt)
an error issue had happen :

File /home/genome/ass/chi/hic/01.X101SC23102206-Z01-J001_hic_clean/combine/chick/result/AutoHiC/hic_results/3d-dna/contig.0.hic cannot be opened for reading

can you help me fix it :?

**Comment by Jwindler** [comment]
From your log, we can see that your environment is configured correctly and is running in GPU mode. But there seems to be a problem when running the `Juicer` step. You should check whether `Juicer` is installed correctly. If convenient, please provide your `configure.txt` file for DEBUG. You can refer to: https://github.com/Jwindler/AutoHiC/issues/13

**Comment by lstxmu** [comment]
Hi, the isssue still happen.
I have follow the jucier install instruction "https://github.com/aidenlab/juicer/wiki/Installation"  and run agian, but nothing changed.
please help me fix it. Looking for your help.
Sincerely.
Site Luo
[cfg-autohic.txt](https://github.com/Jwindler/AutoHiC/files/13712365/cfg-autohic.txt)

**Comment by Jwindler** [comment]
maybe : `JUICER_DIR=/home/genome/soft/juicer/scripts` > `JUICER_DIR=/home/genome/soft/juicer`

**Comment by lstxmu** [comment]
Thanks for your suggestion. After changed JUICER_DIR, the assemble run works.  

Thank you.

Site Luo

**Comment by lstxmu** [comment]
Hi, after jucier issue fix. another issue happen , the error message was follow "/home/genome/lstdata/ass/chi/hic/01.X101SC23102206-Z01-J001_hic_clean/combine/chick/result/AutoHiC/hic_results/3d-dna/contig.0.hic cannot be opened for reading"   ,  can you help me  fix it ?

[log.txt](https://github.com/Jwindler/AutoHiC/files/13721083/log.txt)
[cfg-autohic.txt](https://github.com/Jwindler/AutoHiC/files/13721084/cfg-autohic.txt)

**Comment by Jwindler** [comment]
There is a `logs` folder in your results folder. Please check the log information in it, or provide it to me to help you check.

**Comment by lstxmu** [comment]
ok,please help me chek the log file. Thanks a lot.
[3d-dna.log](https://github.com/Jwindler/AutoHiC/files/13721691/3d-dna.log)
[bwa_index.log](https://github.com/Jwindler/AutoHiC/files/13721692/bwa_index.log)
[juicer.log](https://github.com/Jwindler/AutoHiC/files/13721693/juicer.log)

**Comment by Jwindler** [comment]
As shown in the picture below, your juicer cannot find the `statistics` command. Not sure what version of jucier you are using, my suggestion is to use the juicer I provided in `README`.

![image](https://github.com/Jwindler/AutoHiC/assets/41459206/3d127482-d3f4-4f27-ac46-7d9541b7628d)

**Comment by lstxmu** [comment]
i replace the jucier and 3d-dna  verion from your shared files,  but run fail again. Can you check the log file and give more suggestion?
[Uploading 3d-dna.log…]()

**Comment by Jwindler** [comment]
Please provide me with all the log files you ran after the replacement.

**Comment by lstxmu** [comment]
[l
[3d-dna.log](https://github.com/Jwindler/AutoHiC/files/13722467/3d-dna.log)
[bwa_index.log](https://github.com/Jwindler/AutoHiC/files/13722468/bwa_index.log)
[juicer.log](https://github.com/Jwindler/AutoHiC/files/13722469/juicer.log)
[log.txt](https://github.com/Jwindler/AutoHiC/files/13722470/log.txt)

**Comment by Jwindler** [comment]
As shown in the log below, when you rerun `AutoHiC`, you need to delete the previous error result files. Please make sure that only the files and folders that need to be entered exist.

![image](https://github.com/Jwindler/AutoHiC/assets/41459206/0fd7432b-17e8-41fc-a54c-b328c5a02b6f)
