### ISSUE TITLE
Run in cpu mode , a error hadd occur, please help fix it.

### ISSUE THREAD

**Issue by lstxmu** [Jwindler/AutoHiC#15]
Hi, I run the assebly in cpu mode, and got a error occur as follow.

TypeError: __init__() got an unexpected keyword argument 'pretrained'

Can you help me fix it ?

Thank you.
[3d-dna.log](https://github.com/Jwindler/AutoHiC/files/13740682/3d-dna.log)
[bwa_index.log](https://github.com/Jwindler/AutoHiC/files/13740684/bwa_index.log)
[cfg-autohic.txt](https://github.com/Jwindler/AutoHiC/files/13740685/cfg-autohic.txt)
[juicer.log](https://github.com/Jwindler/AutoHiC/files/13740686/juicer.log)
[log.txt](https://github.com/Jwindler/AutoHiC/files/13740687/log.txt)

**Comment by Jwindler** [comment]
As you can see from your log, this problem occurs due to software installation problems. You can try running the following command.
```sh

# configuration environment
cd AutoHiC/src/models/swin

# install dependencies
pip install -e . -i https://pypi.tuna.tsinghua.edu.cn/simple/

```
