### ISSUE TITLE
Files in chromosome directory

### ISSUE THREAD

**Issue by shig913** [Jwindler/AutoHiC#16]
Thank you for this great tool!
I want to know files in the directory, autohic_results/chromosome.
What do the files xxx_final.fasta and xxx_FINAL.fasta mean?

**Comment by Jwindler** [comment]
You can compare their sequence lengths and names to see the difference. Generally speaking, `xxx_FINAL.fasta` differentiates scaffolds, merges contigs, and changes sequence names.
