### ISSUE TITLE
The number of obtained chromosomes does not match the actual count

### ISSUE THREAD

**Issue by lstxmu** [Jwindler/AutoHiC#17]
The genome has 39 pairs of chromosomes, but after assembly, only 13 were obtained. Could you please indicate where the differences occurred? Results file has been submitted for inspection. 
[result.zip](https://github.com/Jwindler/AutoHiC/files/13768287/result.zip)

**Comment by Jwindler** [comment]
We are very sorry. The number of chromosomes in your genome is relatively complex and the number of chromosomes cannot be determined automatically. It is recommended that you manually determine the number and length of chromosomes in juicebox based on the final .hic file.
> [Split chromosome (optional)](https://github.com/Jwindler/AutoHiC#split-chromosome-optional)
