### ISSUE TITLE
 File XXXX/autohic_results/3/XXXX.final.hic cannot be opened for reading

### ISSUE THREAD

**Issue by mcariou** [Jwindler/AutoHiC#20]
Hello,

I am using AutoHiC through docker.
I met an issue that looks like the one desribed in #5

```
[2024-03-26  16:04:00] hic_adv_model.py -> __init__ line:40 [INFO] : Create genome folder: /home/autohic/<PATH>/result/AutoHiC/autohic_results/3/png

File /home/autohic/<PATH>/result/AutoHiC/autohic_results/3/Pfai_hap1.final.hic cannot be opened for reading
```
However, in this case it was resolved by writing the fasta contig file in 80bp line, and mine is already in that format. I can't find any other difference between my format and that of the example dataset.

the command was:
```
nohup python3.9 autohic.py -c /home/autohic/cfg-autohic_Pfai.txt > /home/autohic/log4.txt 2>&1
```

Here is the log file and config file
[cfg-autohic_Pfai.txt](https://github.com/Jwindler/AutoHiC/files/14762528/cfg-autohic_Pfai.txt)
[log4.txt](https://github.com/Jwindler/AutoHiC/files/14762529/log4.txt)

I thank you in advance for any suggestion regarding the origin of the issue.

Best regards

**Comment by Jwindler** [comment]
<img width="1145" alt="image" src="https://github.com/Jwindler/AutoHiC/assets/41459206/b6218296-3bae-438e-abe2-c6891d8dc946">

 
If you've used AutoHiC before, please make sure to delete any previously generated results and run the program again. Also, be sure to review the logs in the results folder to address any potential issues.

**Comment by mcariou** [comment]
Hello,

Many thanks for your advice, I will follow it from now on.

I rerun the same config file, after deleting completely the "results" folder and anything not the fastq files in the "rawdata" folder.
The resulting log looks very similar to me except for the two lines you pointed at.

Is there anything I forgot to delete?

Here are the 4 logs:
[log5.txt](https://github.com/Jwindler/AutoHiC/files/14801557/log5.txt)
[3d-dna.log](https://github.com/Jwindler/AutoHiC/files/14801558/3d-dna.log)
[bwa_index.log](https://github.com/Jwindler/AutoHiC/files/14801559/bwa_index.log)
[juicer.log](https://github.com/Jwindler/AutoHiC/files/14801560/juicer.log)

I notice that the last written (3d-dna) ends like this, does that means that this step is completed?

```
Analyzing the merged assembly
...trimming N overhangs
...adding gaps
```

My inputs look like this:

```
$ ls -lh rawdata/fastq/
total 7,2G
-rw-r--r-- 1 mcariou mcariou 3,5G mars  27 10:13 PfaiPoolC1B1_R1.fastq.gz
-rw-r--r-- 1 mcariou mcariou 3,7G mars  27 10:13 PfaiPoolC1B1_R2.fastq.gz
```
These were renamed to match the recommended naming: X_R1.fastq.gz and X_R2.fastq.gz

```
$ ls -lh references/
-rw-r--r-- 1 root    root    149M mars  22 16:41 Pfai_hap1.fasta
$ head references/Pfai_hap1.fasta 
>h1tg000001l
GTACAATATTTGAGCTGAGACGAGCTGGCATCAAACGGAATCCAAATGTTCTTAGTACCCGCGTGTAGAGCTCGTCGAGC
TGAACAAACAAGTAGCAAACTTAACCGAATTGCAGGCCGCTTGCAGTCGTCCCAACTCAAACGCGCTCGGTTACAGTCAG
TTGTACCATATTTTCGATCTGAAGAGCGGCATCAAACGAATCCAAATGTTCTTAGTACCCGCGTTAGAGCTCGTCGAGCT
GAACAAACCAGTAACAAATTTAACCGAATTGCATGGGATCCCAGCTCGTTCCAACTCAAGCGTGCTCTCTTTTACAGTCA
GTTGTACAATATTTGAGCTGAGACGAGCTGGCATCAAACGGGATCCAAATGTTCTTAGTACCCGCGTGTAGAGCTCGTCG
AGCTGAACAAACAAATAGCAAATTTAACCGAATTGCATGGGATCCCAGCTCGTCCCAACTCAAGCGTGCTCTCTTTTACA

```
The genome contig file is a fasta with 80bp lines.

Many thanks in advance for your advices,

Best regards

**Comment by Jwindler** [comment]
Based on your current log, your operation appears to be correct. AutoHiC has detected and corrected an error, but there seems to be an issue when generating the fasta file.
Do you have `/home/autohic/SPECIES/result/AutoHiC/logs/epoch_3.log` file? 
I suspect there may be an issue with your cfg-autohic.txt file. Please upload it so that I can investigate further. Thank you.

**Comment by mcariou** [comment]
Thank you very much!
No, there are only 3 files in the logs:
`/home/autohic/SPECIES/result/AutoHiC/logs/3d-dna.log`,  `/home/autohic/SPECIES/result/AutoHiC/logs/bwa_index.log`  and /`home/autohic/SPECIES/result/AutoHiC/logs/juicer.log`.

Here is my config file:
[cfg-autohic_Pfai.txt](https://github.com/Jwindler/AutoHiC/files/14801880/cfg-autohic_Pfai.txt)

**Comment by Jwindler** [comment]
![image](https://github.com/Jwindler/AutoHiC/assets/41459206/b1f5c1ec-f3cf-4273-b707-92f4852df1b5)
Perhaps you should verify the permissions of the 3D-DNA file and check for the presence of a run-asm-pipeline-post-review.sh file.
Which version of AutoHiC are you using?

**Comment by Jwindler** [comment]
I recommend using version 1.3.1. I added an INFO section to assist with troubleshooting your issue.

**Comment by mcariou** [comment]
I am sorry, what is an INFO section?

Regarding the permissions of the 3d-dna file, here are the files I downloaded from google drive (https://drive.google.com/drive/folders/1T9twnImt1CK_NrB9SBb-dg4dBENyhPTN), and put where I mounted the docker.
![Capture_autohic](https://github.com/Jwindler/AutoHiC/assets/74544784/58979f18-420a-4364-9d8d-e1d01ecf9f11)

Is that alright?

Where would I find the run-asm-pipeline-post-review.sh file? Should it be in the same folder autohic.py is? In this case I don't have it.

Regarding the version, how can I check that? (not `python3.9 autohic.py --version`) I pulled the docker about a week ago (20/03/2024), so I supposed it might be the latest version.

Thanks again

**Comment by Jwindler** [comment]
If you are in Docker, please git clone again and then run AutoHiC. As usual, the previous results file needs to be deleted.

**Comment by Jwindler** [comment]
`run-asm-pipeline-post-review.sh` should in your `/home/autohic/3d-dna/`

**Comment by mcariou** [comment]
Hello,

> run-asm-pipeline-post-review.sh should in your /home/autohic/3d-dna/

Ah yes, it is, and the permission to run it seems ok.

![capture](https://github.com/Jwindler/AutoHiC/assets/74544784/2cde143f-31f0-447e-a0f5-689232e106ce)


> If you are in Docker, please git clone again and then run AutoHiC. As usual, the previous results file needs to be deleted.

Thanks I cloned it and restarted the calcul, there are small differences in the logs, but the final stage seems similar:

[log6.txt](https://github.com/Jwindler/AutoHiC/files/14833297/log6.txt)
[3d-dna.log](https://github.com/Jwindler/AutoHiC/files/14833298/3d-dna.log)
[bwa_index.log](https://github.com/Jwindler/AutoHiC/files/14833299/bwa_index.log)
[juicer.log](https://github.com/Jwindler/AutoHiC/files/14833301/juicer.log)

**Comment by Jwindler** [comment]
Great, I should know what your problem is now. In your log file:
`[2024-03-29  17:30:16] autohic.py -> whole line:241 [INFO] : Run command : bash /home/autohic/3d-dna ##### !!!!!!!!!!!!!!!/run-asm-pipeline-post-review.sh -r /home/autohic/SPECIES/result/AutoHiC/autohic_results/3/test.assembly /home/autohic/SPECIES/references/Pfai_hap1.fasta /home/autohic/SPECIES/result/AutoHiC/hic_results/juicer/Pfai_hap1/aligned/merged_nodups.txt > /home/autohic/SPECIES/result/AutoHiC/logs/epoch_3.log 2>&1
`
In your `cfg-autohic_Pfai.txt` file, there should be a problem with `TD_DNA_DIR`.

The file（`cfg-autohic_Pfai.txt`） should be edited to replace the downloaded file, but no additional lines should be added. Only modify the paths to the software and data.

**Comment by Jwindler** [comment]
`TD_DNA_DIR` is your 3d-dna install path

**Comment by mcariou** [comment]
Oh right, it works!
Thank you very much! I thought I just added a commentary for lines I wasn't sure about in the config file. Never thought it would end up in a path.

Thank you very much again for the help and patience in troubleshooting!
