### ISSUE TITLE
IndexError: cannot do a non-empty take from an empty axes.

### ISSUE THREAD

**Issue by 1538501175** [Jwindler/AutoHiC#21]
Hello,
I was testing the genome of a diploid animal with AutoHiC, and it has successfully run Juicer and 3D-DNA. However,  the program stopped during the second round of execution, and the result files are as follows:

`/lustre/home/geneticstest/hdx/cercopithecus/assembly/Hic/autohic/hongwei/result/AutoHiC_hongwei/autohic_results/2] 
$ ls 
chr_len_filtered_errors.json  debris_error.json   infer_result              len_filtered_errors.xlsx      overlap_filtered_errors.xlsx  score_filtered_errors.xlsx
chr_len_filtered_errors.xlsx  error_summary.json  inversion_error.json      len_remove_error.xlsx         overlap_remove_error.txt      zoomed_errors.json
chr_len_remove_error.txt      error_summary.xlsx  len_filtered_errors.json  overlap_filtered_errors.json  png
`
The error information in the log file is as follows:
`                                                                           │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │              arr = array([], dtype=float64)                              │ │
│ │             axis = 0                                                     │ │
│ │        DATA_AXIS = 0                                                     │ │
│ │           method = {                                                     │ │
│ │                    │   'get_virtual_index': <function <lambda> at        │ │
│ │                    0x7fd4b49fd1f0>,                                      │ │
│ │                    │   'fix_gamma': <function <lambda> at                │ │
│ │                    0x7fd4b49fd280>                                       │ │
│ │                    }                                                     │ │
│ │     next_indexes = array(0)                                              │ │
│ │              out = None                                                  │ │
│ │ previous_indexes = array(0)                                              │ │
│ │        quantiles = array(0.95)                                           │ │
│ │     values_count = 0                                                     │ │
│ │  virtual_indexes = array(-0.95)                                          │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│ in take:200                                                                  │
│ ╭──────────────────────────── locals ────────────────────────────╮           │
│ │           args = (array([], dtype=float64),)                   │           │
│ │     dispatcher = <function _take_dispatcher at 0x7fd4b4bb93a0> │           │
│ │ implementation = <function take at 0x7fd4b4bb94c0>             │           │
│ │         kwargs = {'indices': -1, 'axis': 0}                    │           │
│ │     public_api = <function take at 0x7fd4b4bb9550>             │           │
│ │  relevant_args = (array([], dtype=float64), None)              │           │
│ │       use_like = False                                         │           │
│ ╰────────────────────────────────────────────────────────────────╯           │
│                                                                              │
│ /lustre/home/geneticstest/mambaforge-pypy3/envs/autohic/lib/python3.9/site-p │
│ ackages/numpy/core/fromnumeric.py:190 in take                                │
│                                                                              │
│    187 │   array([[4, 3],                                                    │
│    188 │   │      [5, 7]])                                                   │
│    189 │   """                                                               │
│ ❱  190 │   return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mod │
│    191                                                                       │
│    192                                                                       │
│    193 def _reshape_dispatcher(a, newshape, order=None):                     │
│                                                                              │
│ ╭────────────── locals ──────────────╮                                       │
│ │       a = array([], dtype=float64) │                                       │
│ │    axis = 0                        │                                       │
│ │ indices = -1                       │                                       │
│ │    mode = 'raise'                  │                                       │
│ │     out = None                     │                                       │
│ ╰────────────────────────────────────╯                                       │
│                                                                              │
│ /lustre/home/geneticstest/mambaforge-pypy3/envs/autohic/lib/python3.9/site-p │
│ ackages/numpy/core/fromnumeric.py:57 in _wrapfunc                            │
│                                                                              │
│     54 │   │   return _wrapit(obj, method, *args, **kwds)                    │
│     55 │                                                                     │
│     56 │   try:                                                              │
│ ❱   57 │   │   return bound(*args, **kwds)                                   │
│     58 │   except TypeError:                                                 │
│     59 │   │   # A TypeError occurs if the object does have such a method in │
│     60 │   │   # class, but its signature is not identical to that of NumPy' │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │   args = (-1,)                                                           │ │
│ │  bound = <built-in method take of numpy.ndarray object at                │ │
│ │          0x7fd499594f90>                                                 │ │
│ │   kwds = {'axis': 0, 'out': None, 'mode': 'raise'}                       │ │
│ │ method = 'take'                                                          │ │
│ │    obj = array([], dtype=float64)                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────╯
IndexError: cannot do a non-empty take from an empty axes.
`

Here attached the configuration file and the log file.  
[hongwei_autohic.txt](https://github.com/Jwindler/AutoHiC/files/14885416/hongwei_autohic.txt)
[log.txt](https://github.com/Jwindler/AutoHiC/files/14885270/log.txt)
Could you please help me figure out what might be causing this issue? Besides, Would using the .hic file from the hic_results/3d-dna results folder to continue running onehic.py make a difference compared to the final autohic result?

Thank you very much for helping me solve this problem

**Comment by Jwindler** [comment]
Based on your log file, I have identified `File doesn't have the given chr_chr map 1_1`. Although this situation is new to me, I kindly request that you upload the file under `logs` (path:`/lustre/home/geneticstest/hdx/cercopithecus/assembly/Hic/autohic/hongwei/result/AutoHiC_hongwei/logs/*
`) in your results so that I can analyze this error.

**Comment by 1538501175** [comment]
[bwa_index.log](https://github.com/Jwindler/AutoHiC/files/14886894/bwa_index.log)
[juicer.log](https://github.com/Jwindler/AutoHiC/files/14886895/juicer.log)
[3d-dna.log](https://github.com/Jwindler/AutoHiC/files/14886897/3d-dna.log)
Here are the all logs in this folder. Thank you very much for your response. I have already added your contact information.
