### ISSUE TITLE
Failure during chimera handling

### ISSUE THREAD

**Issue by gargkritika** [Jwindler/AutoHiC#25]
Hi

I was able to install the conda version of AutoHiC correctly. However, the program crashed after running the juicer step. This is the last few lines of the juicer log file. Please let me know if you need me to send you the entire log file as well.

[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -SP5M -t 40 /data3/balaji/rhinolophus_raw_genome/scaffolding/5_auto_hic/results_rhinolophus/AutoHiC_rhinolophus/data/reference/rename_genome.fasta /data3/balaji/rhinolophus_raw_genome/scaffolding/5_auto_hic/results_rhinolophus/AutoHiC_rhinolophus/hic_results/juicer/rename_genome/splits/clean_hic_R1.fastq.gz /data3/balaji/rhinolophus_raw_genome/scaffolding/5_auto_hic/results_rhinolophus/AutoHiC_rhinolophus/hic_results/juicer/rename_genome/splits/clean_hic_R2.fastq.gz
[main] Real time: 31742.853 sec; CPU: 411122.844 sec
(-:  Align of /data3/balaji/rhinolophus_raw_genome/scaffolding/5_auto_hic/results_rhinolophus/AutoHiC_rhinolophus/hic_results/juicer/rename_genome/splits/clean_hic.fastq.gz.sam done successfully
awk: /data3/balaji/rhinolophus_raw_genome/scaffolding/5_auto_hic/juicer/scripts/common/chimeric_blacklist.awk: line 671: function and never defined
awk: /data3/balaji/rhinolophus_raw_genome/scaffolding/5_auto_hic/juicer/scripts/common/chimeric_blacklist.awk: line 671: function and never defined
awk: /data3/balaji/rhinolophus_raw_genome/scaffolding/5_auto_hic/juicer/scripts/common/chimeric_blacklist.awk: line 671: function and never defined
awk: /data3/balaji/rhinolophus_raw_genome/scaffolding/5_auto_hic/juicer/scripts/common/chimeric_blacklist.awk: line 671: function and never defined
awk: /data3/balaji/rhinolophus_raw_genome/scaffolding/5_auto_hic/juicer/scripts/common/chimeric_blacklist.awk: line 671: function and never defined
***! Failure during chimera handling of /data3/balaji/rhinolophus_raw_genome/scaffolding/5_auto_hic/results_rhinolophus/AutoHiC_rhinolophus/hic_results/juicer/rename_genome/splits/clean_hic.fastq.gz

Thank you
Best
Kritika

**Comment by Jwindler** [comment]
Looks like AutoHiC is working well. To fix this, you'll need to install gawk(`sudo apt install gawk`) on your system. When you run AutoHiC again, make sure to delete all the files it created before.

**Comment by gargkritika** [comment]
Hi 

I have installed gawk and now it is running. I will keep you posted if I run into any further errors.

Thank you
