### ISSUE TITLE
usage of  onehic

### ISSUE THREAD

**Issue by hylu-coder** [Jwindler/AutoHiC#27]
Hi,

I have intalled AutoHic successfully,but can't find the  file pretrained.pth.
# run onehic
python3.9 onehic.py -hic test.hic -asy test.assembly -autohic /home/ubuntu/AutoHic -p pretrained.pth -out ./

**Comment by Jwindler** [comment]
you should download pretrained file from : https://github.com/Jwindler/AutoHiC?tab=readme-ov-file#pre-trained-model-download
