### ISSUE TITLE
singularity build error

### ISSUE THREAD

**Issue by Liyong-Zhang** [Jwindler/AutoHiC#29]
Hi there, 

I am trying to install AutoHiC on HPC through singularity.
After manually download the AutoHiC.sif from https://drive.google.com/drive/folders/1IADgGUgfSFyp8tQ6Nco_9g_pWCqGBPOe
I run `singularity build autohiC.sif AutoHiC.sif`, it shows
**_WARNING: No default remote in use, falling back to default keyserver: https://keys.openpgp.org
INFO:    Starting build...
INFO:    Verifying bootstrap image AutoHiC.sif
WARNING: failed to get key material: 404 Not Found
WARNING: integrity: 1 error occurred:
        * signature object 4 not valid: openpgp: signature made by unknown entity
WARNING: Bootstrap image could not be verified, but build will continue._**
INFO:    Creating SIF file...
INFO:    Build complete: autohiC.sif

I still try to use the SIF file after that:
`singularity exec autohiC.sif bash`
INFO:    underlay of /etc/localtime required more than 50 (113) bind mounts
Apptainer> `cd /home/autohic/`
Apptainer> `git clone https://github.com/Jwindler/AutoHiC.git`

I got the following error:
**fatal: could not create work tree dir 'AutoHiC': Function not implemented**

Please help me take a look when you get a chance.   Thank you!

**Comment by Jwindler** [comment]
we have not encountered this error. we suggest you install AutoHiC with [conda](https://github.com/Jwindler/AutoHiC?tab=readme-ov-file#conda). We will test singularity in later, if we find problem, I will let you know.

**Comment by Liyong-Zhang** [comment]
Sounds good.  I will try conda.   Thanks.

**Comment by Jwindler** [comment]
We found the same problem, we will test and fix it soon.

**Comment by Liyong-Zhang** [comment]
Thanks for the update.

**Comment by Jwindler** [comment]
Now we fix it, you can refer: https://github.com/Jwindler/AutoHiC/blob/main/example/singularity_autohic.md#autohic-singularity-version

**Comment by Liyong-Zhang** [comment]
Sounds good. thanks, I will give it another try.
