### ISSUE TITLE
Run Juicer 

### ISSUE THREAD

**Issue by gqy20** [Jwindler/AutoHiC#38]
Hi,
   I currently have multiple HiFi sequencing datasets and a set of Hi-C data. I will mount these HiFi data respectively using this set of Hi-C data. When running autohic, do I need to rerun juicer each time, or can I use the sam file from the first run to mount it in autohic?

**Comment by Jwindler** [comment]
AutoHiC uses HiC and genome files, not HiFi sequencing data

**Comment by gqy20** [comment]
> AutoHiC uses HiC and genome files, not HiFi sequencing data

Sorry, I mean the contig file is assembled using hifi data, all of these data come from the same species.

**Comment by Jwindler** [comment]
Well, if you have multiple genomes to scaffold, you should run AutoHIC every time.

**Comment by gqy20** [comment]
OK. Thank you very much.
