### ISSUE TITLE
Why only accept juicer+3d-dna results?

### ISSUE THREAD

**Issue by xiekunwhy** [Jwindler/AutoHiC#4]
Hi,

Juicer and 3d-dna are so slow, why don't accept other software results, like YaHS, SALSA2 results ?

Best,
Kun

**Comment by Jwindler** [comment]
We originally developed it based on Juicebox, and since 3d-dna is widely used, this version currently only supports 3d-dna. However, it seems that users using other assembly software can switch to 3D-DNA. Thank you for your suggestion, we may update this in the future.

**Comment by Jwindler** [comment]
> Hi,
> 
> Juicer and 3d-dna are so slow, why don't accept other software results, like YaHS, SALSA2 results ?
> 
> Best, Kun

maybe you can ref to : https://github.com/Jwindler/AutoHiC/blob/main/example/other_tools.md

**Comment by xiekunwhy** [comment]
Ok，thank you very much!
