### ISSUE TITLE
What is the disadvantage of setting very large ERROR_MAX_LEN?

### ISSUE THREAD

**Issue by shelkmike** [Jwindler/AutoHiC#41]
By default, ERROR_MAX_LEN is 20 megabases. I want AutoHiC to fix arbitrarily long errors. So I set ERROR_MAX_LEN to 100 gigabases. Are there any pitfalls in doing so? Why is ERROR_MAX_LEN limited by default?

**Comment by Jwindler** [comment]
In fact, there are usually not such long errors unless the previous assembly is completely wrong. AutoHiC sets this parameter to avoid identifying the entire chromosome as a translocation error.
