### ISSUE TITLE
What is the difference between contig_autohic.fasta, contig.FINAL.fasta and contig.final.fasta

### ISSUE THREAD

**Issue by shelkmike** [Jwindler/AutoHiC#42]
AutoHiC writes 3 FASTA files to the folder "chromosome": contig_autohic.fasta, contig.FINAL.fasta, contig.final.fasta. Could you please explain in detail the difference between them?

**Comment by Jwindler** [comment]
![image](https://github.com/user-attachments/assets/5369f3e6-1527-4fc4-b29f-c52e65eccb41)

**Comment by shelkmike** [comment]
I saw this, but this doesn't answer my question.

**Comment by Jwindler** [comment]
`contig_autohic.fasta`: chromosome-length scaffolds (removed the sequence unscaffolded)
`contig.FINAL.fasta, contig.final.fasta`: “FINAL” – chromosome-length scaffolds; “final” – input with all the misjoin correction introduced;
