### ISSUE TITLE
Some prerequisites for successful operation

### ISSUE THREAD

**Issue by XXH123a** [Jwindler/AutoHiC#6]
Hi, a creative developer
I am very happy to try this latest scaffolding tool, but before I start, I still want to ask you a small question. For a 3.3G hybrid plant genome, whether only 45x Hi-C data meets the requirements and how large a hard disk is required for operation (because my hard disk is only 1t)

**Comment by Jwindler** [comment]
To be honest, in my experience, the 45X Hi-C data seems a bit insufficient for hybrid plants. Maybe in my opinion 5T of hard disk space can be enough.
