### ISSUE TITLE
error

### ISSUE THREAD

**Issue by taotaoyuan** [Jwindler/AutoHiC#7]
Traceback (most recent call last):
  File "/home/lx_sky6/yt/soft/AutoHiC/onehic.py", line 14, in <module>
    import torch
  File "/home/lx_sky6/yt/soft/miniconda3/envs/autohic/lib/python3.9/site-packages/torch/__init__.py", line 197, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/lx_sky6/yt/soft/miniconda3/envs/autohic/lib/python3.9/site-packages/torch/lib/../../../../libgomp.so.1: version `GOMP_4.0' not found (required by /home/lx_sky6/yt/soft/miniconda3/envs/autohic/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)

**Comment by Jwindler** [comment]
This seems to be an issue with the gcc version. It is recommended to use the Docker version of the AutoHiC environment, or see the link below:
1. https://tissue333.gitbook.io/cornell/findings/pytorch_version
2. https://blog.csdn.net/fish_chuncick/article/details/121636281
