### ISSUE TITLE
Docker Container doesn't contain the code.

### ISSUE THREAD

**Issue by dslater82** [Jwindler/AutoHiC#8]
In the docker image, we have to git clone the code and activate the conda environment.  The point of a docker container is to have everything in there so we can just run the program.   Can you git clone the code in there.  

For us on a HPC cluster, user's can not edit docker containers.  We have to convert it to a singularity container anyway to make it work for us.  

Thanks.

**Comment by Jwindler** [comment]
Thanks for your suggestion. Since AutoHiC is currently updated very fast, it is not included in the Docker image. Docker only provides a runtime environment. In addition, for cluster users, we are testing the singularity image and will release it soon.

**Comment by Jwindler** [comment]
Now you can follow the link （https://github.com/Jwindler/AutoHiC/blob/main/example/singularity_autohic.md）  to run AutoHiC on the cluster. If you have any questions, feedback is welcome, thank you.

**Comment by dslater82** [comment]
Thank you.  I'll give the singularity image a shot.
