### ISSUE TITLE
Error with GPU/CUDA

### ISSUE THREAD

**Issue by kiratalreja3** [Jwindler/AutoHiC#9]
Hi, I get this error while trying to use AutoHiC latest version 

RuntimeError: nms is not compiled with GPU support

Seems like it is related to mmcv/mmdet - I have tried every possible step trying to solve this error but seems like I just can't. Can you please help>?

**Comment by Jwindler** [comment]
Thank you for your response.
If you want to use GPU, please install [CUDA-11.3](https://developer.nvidia.com/cuda-11.3.0-download-archive) and [cuDNN-8.2](https://developer.nvidia.com/rdp/cudnn-archive) before.
For AutoHiC with GPU support, you need to be under the above CUDA version and use conda to reinstall AutoHiC.
If there are no special requirements, it is recommended to use AutoHiC in the CPU environment, which does not change the speed much, because the time limit is mainly concentrated on juier and 3d-dna.

**Comment by kiratalreja3** [comment]
Thanks, I will try that. From my testing, it seems the GPU mode is exponentially faster than CPU mode in onehic mode - where my job finished in 40 mins on GPU mode and more than 16 hours on CPU mode.

**Comment by kiratalreja3** [comment]
Is there a scope of extending the development to YAHS? I am happy to contribute.

**Comment by Jwindler** [comment]
Thank you for your response. We are currently working on this development. If you have any good suggestions, I hope you can keep in touch with me.

**Comment by Jwindler** [comment]
> Is there a scope of extending the development to YAHS? I am happy to contribute.

maybe you can ref to : https://github.com/Jwindler/AutoHiC/blob/main/example/other_tools.md

**Comment by zhangwenda0518** [comment]
Hello, teacher, 
I would like to ask how to check whether my server supports and uses GPU acceleration. I looked up the command **lspci | grep -i VGA** on the Internet.
My server shows: 
62: 00.0 VGA compatible controller: Matrox Electronics Systems Ltd. Integrated Matrox G200EW 3 Graphics Controller (Rev 04).

Does this mean that my server can use GPU acceleration? What should I do next?
Thank you！

**Comment by Jwindler** [comment]
> Hello, teacher, I would like to ask how to check whether my server supports and uses GPU acceleration. I looked up the command **lspci | grep -i VGA** on the Internet. My server shows: 62: 00.0 VGA compatible controller: Matrox Electronics Systems Ltd. Integrated Matrox G200EW 3 Graphics Controller (Rev 04).
> 
> Does this mean that my server can use GPU acceleration? What should I do next? Thank you！

You should make sure that your machine has a graphics card, and install the appropriate driver and CUDA, consulting the documentation for tips. @zhangwenda0518
